### ISSUE TITLE
A suggestion for the section "Adding a second project using Visual Studio 2022" in page 49

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#25]
I have a suggestion for the section _Adding a second project using Visual Studio 2022_ of the _first chapter_ on _page 49_ of the .pdf file. In there (in item 3) it should be noted that in the **Configure your new project** dialog the _Add to solution_ option must be selected not _Create new solution_ which is the default option.

**Comment by markjprice** [comment]
You will only see the additional dorpdown to select between **Add to solution** and **Create new solution** if you have used the menu choice: **File** | **New** | **Project**. If you follow the instruction in Step 1 to select **File** | **Add** | **New Project** then you do not have the dropdown with those two options because you have already told it that you want to "Add" not "Create New".
