### ISSUE TITLE
Output complex numbers using default ToString implementation

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#50]
On page 357, by running the line `WriteLine($"{c1} added to {c2} is {c3}");` I get
`<4; 2> added to <3; 7> is <7; 9>`
instead of
`(4, 2) added to (3, 7) is (7, 9)`

**Comment by markjprice** [comment]
Yes, because number formats are culture-specific. You must live in a country that formats complex numbers using angle brackets and semi-colons instead of round brackets and commas. What country do you live in?

Regardless, I have created an improvement item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-357---working-with-complex-numbers
