### ISSUE TITLE
No instructions on how to create a unit test app

### ISSUE THREAD

**Issue by SevanDY** [markjprice/cs11dotnet7#78]
Chapter: 04: Writing, Debugging and Testing Functions
Page Number: 185
Section Title: Creating a class library that needs testing
Step Number: 5
Problem to fix: There are no instructions on how to create a unit test app in VS Code
Suggested solution: Add `dotnet new xunit` command on that step.
Other useful information e.g. OS, coding tools, and so on: VS Code

**Comment by markjprice** [comment]
Page 186 tells them what project template to use for both Visual Studio 2022 and at the command prompt for Visual Studio Code:
![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/c36886ff-9ecb-4fff-9abc-a99caa9c0c96)
Chapter 1 has step by step instructions that apply to any template, and I even repeat the standard instructions on page 185. The only difference is the template name which I give.

**Comment by SevanDY** [comment]
In the 5th step you just create an empty workspace with no files and in 6th step(VS Code) there is a reference on "CalculatorLibUnitTests.csproj" file. I can't find the step where you create the application. Is it usual console app or xunit app?

I don't find any reference on "xunit" in the 1st chapter.

I guess I am confusing something.

**Comment by markjprice** [comment]
In Step 1, I explain that **Class Library**/`classlib` project to the solution. Creating any project type is the same as creating a console. Instructions in Chapter 1 show how to create a console, not an xunit project, but as I explain in Step 1, the only difference is the project template name. For example, instead of `console`, enter `classlib` or `xunit`.

![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/be9e5262-3303-467d-b579-f3fc4bbff7cd)

I don't know which Step 5 you mean when you say "In the 5th step you just create an empty workspace with no files". Step 5 in the VS Code steps says "In TERMINAL, confirm that you are in the CalculatorLib folder, and then 
enter the command to create a new class library, as shown in the following 
command: dotnet new console." But that already has an errata saying it should be `classlib` not `console`. And the other Step 5 says "Use your preferred coding tool to add a new xUnit Test Project [C#] / xunit project named 
CalculatorLibUnitTests to the Chapter04 workspace/solution." So the reader should know how to do that using `dotnet new xunit` because only the project type name is different and the other steps for adding the new project to the workspace are the same as for a class library or console app.

**Comment by markjprice** [comment]
As I say, by this point the reader has see dozens of steps like the following:

![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/f1724c0b-47f8-4d53-a6e0-47eb4bb560b9)
![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/69a82a7a-84f8-408d-9a32-a5ea67a743eb)
![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/97da341c-23a0-4b75-a905-127c5ffdc7e8)

So they should know that the following is the same but with a different project template name:

![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/ee08a9a9-b93a-459f-a411-2f5a92b43cb2)
