### ISSUE TITLE
Addin `Model` into the Razor page cause error

### ISSUE THREAD

**Issue by cmkaya** [markjprice/cs11dotnet7#82]
Chapter: 13

Page Number: 573 

Section Title: Adding code to a Razor Page

Step Number: 1 and 2

Problem to fix: In the code snippet, the `DayName` is set with the `Model`. But when I write the same, I get the "Cannot resolve symbol 'DayName'". On the other hand, when I remove the `Model`, the problem is fixed. Maybe I am wrong but as much as I know, the `Model` represents the entity models. However, we have not bound `index.cshtml`  with in any entity model.

<img width="505" alt="image" src="https://github.com/markjprice/cs11dotnet7/assets/75931847/7288f04c-d1fa-49b9-a8f4-5cd2519ba0a7">

<img width="526" alt="image" src="https://github.com/markjprice/cs11dotnet7/assets/75931847/cafa4206-e608-46a0-af27-476bb6585e86">

**Comment by markjprice** [comment]
When you create a Razor Page where the file is named `index.cshtml` then a class is defined for you named `Pages_index`, as you can see in the screenshot below. It will have a property named `Model` that is the same type. If you add properties to the `@functions` block, you are adding those properties to the `Pages_index` class. Because the class itself is the same thing as its own `Model` property, you can also use `this` or even nothing to refer to the current instance. So `Model.DayName`, `this.DayName`, and `DayName` all refer to the same property.

![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/c9fdfe63-a677-453e-8f94-1de4b4c90679)

As to why your tool says `"Cannot resolve symbol 'DayName'"`, I don't know. What are you using?

**Comment by cmkaya** [comment]
Thank you for the detailed explanation. I have limited knowledge of MVC, and it seems like I've gotten some concepts mixed up :)

I'm using Rider. Here's the structure of the program and the error I mentioned:
<img width="1512" alt="Screenshot 2023-08-27 at 21 12 37" src="https://github.com/markjprice/cs11dotnet7/assets/75931847/c074b989-d1e1-4596-ae30-71826b9d441d">
<img width="512" alt="Screenshot 2023-08-27 at 21 22 16" src="https://github.com/markjprice/cs11dotnet7/assets/75931847/b12791d0-cc74-41bc-a183-c86df7d42a5b">



As I understand it, when I copy the `index.html` file into the Pages folder and then rename it as `index.cshtml`, it doesn't generate an `index.cshtml.cs` file. As a result, the `Model` is not recognized within the `index.cshtml` file.

By the way, I double-checked this. In the book, there is only a statement suggesting modifying the name of `index.html`. There isn't any information provided on adding a Razor page named `index`. I'm not familiar with Visual Studio, but in Rider, I have to explicitly add a Razor page.

<img width="1143" alt="image" src="https://github.com/markjprice/cs11dotnet7/assets/75931847/18a3de84-f733-46c5-8dd7-7d276d8105b9">


Thank you for your help.

**Comment by markjprice** [comment]
In the next edition, I will update the note on page 573 to say that Rider has the same bug as ReSharper:
![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/3ff30f55-d80b-4493-9550-4e4d22e0f03b)

**Comment by cmkaya** [comment]
Thank you so much for the detailed explanation.
